kind: pipeline
type: docker
name: unit

workspace:
  path: /cgrates

steps:
# - name: unit
#   pull: never
#   image: cgrates-integration
#   commands:
#   - go test ./utils
- name: notify
  image: drillster/drone-email
  settings:
    from: arber.katellari@itsyscom.com
    host: smtp.gmail.com
    username: 
      from_secret: email_username
    password: 
      from_secret: email_password
    recipients:
      - arber0katellari@gmail.com
  when:
      status:
      - success
      - failure